### ISSUE TITLE
XCode build link phase lasts too long

### ISSUE THREAD

**Issue by matuskopo** [Anyline/anyline-ocr-examples-ios#15] opened 2020-10-23 09:42 UTC
Hi,
thanks for this library, but we found out our builds started to take much more time then before. We tried to build our project without Anyline Pod, and the link phase takes up to 5 seconds. But with Anyline installed, it's always more then 110 seconds. And that's too much. It doesn't matter if we build it using XCode 11 or 12. Same results. The same happens for AnylineExamples project. We even use FirebaseMLVision Pod and many others, but they are not causing those problems, as without Anyline it's 5 seconds maximum for linking phase.

Bye

**Comment by akaraul** [comment] 2020-12-11 07:32
I have the same problem

**Comment by davlhd** [comment] 2020-12-11 09:07
Hello,
we will have a look at the problem and try to improve link times with the next release.

**Comment by philippAnyline** [comment] 2021-03-17 10:12
@akaraul we improved this in version 27, could you please give us feedback if the issue is resolved for you? 
Thanks, Philipp

**Comment by akaraul** [comment] 2021-03-17 12:25
@philippAnyline yes, the issue resolved. Thanks

**Comment by philippAnyline** [comment] 2021-03-17 14:03
Glad to hear so :) Closing the issue

**Closed by philippAnyline** 2021-03-17 14:03 UTC
