### ISSUE TITLE
[ALScanViewPluginConfig scanViewPluginConfig]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by tvhimanshu** [Anyline/anyline-ocr-examples-ios#9] opened 2019-07-17 06:30 UTC
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ALScanViewPluginConfig scanViewPluginConfig]: unrecognized selector sent to instance 0x281150b60'
*** First throw call stack:

**Comment by melaniamuir** [comment] 2019-07-17 14:39
Hi, 

In order to investigate the issue we need some more information. Please fill out the missing information below.

**Anyline Plugin version:**


**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] general question

**Occurring on ...**
[ ] Android
[X] iOS

**Current behavior:**


**Expected behavior:**


Thank you,
Melania

**Comment by philippAnyline** [comment] 2019-11-27 13:04
I'll close this issue, since there was no proper bugreport since July

**Closed by philippAnyline** 2019-11-27 13:04 UTC
